"""Turing Synthetic Radar Dataset -> a replay scenario for EWEnvironment.

OPTIONAL EXTENSION, OFF BY DEFAULT. PRD Section 25 states that all data is synthetic and
generated by the simulator, and that no external datasets are used. This module does not change
that default: nothing in the training or evaluation path imports it. It exists so the same
agents can be exercised against recorded pulse timing when someone deliberately asks for it.

The dataset (``alan-turing-institute/turing-synthetic-radar-dataset``, Apache-2.0) is a
deinterleaving benchmark: interleaved radar pulse trains described by Pulse Descriptor Words --
time of arrival, frequency, pulse width, amplitude, angle of arrival.

TWO PRACTICAL FACTS that shape this code:

* The repo is **gated**. ``huggingface_hub`` needs a token from an account that has accepted the
  terms on the dataset page. Set ``HF_TOKEN`` (or run ``hf auth login``).
* It ships as **~2,750 raw HDF5 files** under ``archive/train/`` and ``archive/test/``, not as a
  tabular dataset with a loading script. ``datasets.load_dataset(..., streaming=True)`` does not
  give you named ``Time of Arrival`` / ``Centre Frequency`` columns here; the working approach is
  ``hf_hub_download`` on individual ``.h5`` files plus ``h5py``.

HOW THIS CONNECTS BACK TO THE ENVIRONMENT. ``build_replay_ground_truth`` bins PDW centre
frequencies into N bands and quantises time-of-arrival into simulation steps, producing exactly
the ``(T, N)`` occupancy table ``GroundTruth`` already speaks. Handing that to ``EWEnvironment``
via ``ground_truth=`` swaps the synthetic emitter model for recorded pulse timing and changes
nothing else -- same observation vector, same reward, same agents, same metrics.

    from ml.data.turing_replay import load_replay_scenario
    env = load_replay_scenario(num_bands=16, num_files=4)

Field names inside the HDF5 files are discovered at runtime rather than hardcoded, because the
schema is not part of any contract we control.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Iterable, Sequence

import numpy as np

REPO_ID = "alan-turing-institute/turing-synthetic-radar-dataset"
REPO_TYPE = "dataset"

# Candidate names for the two PDW fields we need, lowercased and stripped of separators.
TOA_ALIASES = ("toa", "timeofarrival", "arrivaltime", "time", "t")
FREQ_ALIASES = ("centrefrequency", "centerfrequency", "frequency", "freq", "rf", "carrierfrequency")


class TuringDatasetUnavailable(RuntimeError):
    """Raised with actionable guidance when the gated dataset cannot be reached."""


def _normalise(name: str) -> str:
    return "".join(ch for ch in str(name).lower() if ch.isalnum())


def download_pulse_trains(
    num_files: int = 1, split: str = "train", token: str | None = None, cache_dir: str | None = None
) -> list[Path]:
    """Fetch a few ``.h5`` pulse-train files. Requires an HF token and accepted dataset terms."""
    try:
        from huggingface_hub import hf_hub_download
        from huggingface_hub.errors import GatedRepoError, RepositoryNotFoundError
    except ImportError as exc:  # pragma: no cover - dependency guard
        raise TuringDatasetUnavailable(
            "huggingface_hub is required for the Turing replay scenario: pip install huggingface_hub"
        ) from exc

    token = token or os.environ.get("HF_TOKEN") or os.environ.get("HUGGING_FACE_HUB_TOKEN")
    paths: list[Path] = []
    for i in range(num_files):
        filename = f"archive/{split}/{split}_{i}.h5"
        try:
            paths.append(
                Path(hf_hub_download(REPO_ID, filename, repo_type=REPO_TYPE, token=token,
                                     cache_dir=cache_dir))
            )
        except GatedRepoError as exc:
            raise TuringDatasetUnavailable(
                f"{REPO_ID} is a gated dataset. Accept the terms at "
                f"https://huggingface.co/datasets/{REPO_ID} with your Hugging Face account, then "
                "set HF_TOKEN (or run `hf auth login`) before retrying."
            ) from exc
        except RepositoryNotFoundError as exc:
            raise TuringDatasetUnavailable(
                f"Could not reach {REPO_ID}/{filename}. Check network access and that HF_TOKEN "
                "belongs to an account that has accepted the dataset terms."
            ) from exc
    return paths


def extract_pdw_features(path: str | Path) -> dict[str, np.ndarray]:
    """Read one ``.h5`` pulse train and return its time-of-arrival and centre-frequency arrays.

    The dataset schema is external and not covered by API_CONTRACT.md, so field names are matched
    by alias at runtime and the failure message lists what was actually found.
    """
    try:
        import h5py
    except ImportError as exc:  # pragma: no cover - dependency guard
        raise TuringDatasetUnavailable(
            "h5py is required to read Turing pulse trains: pip install h5py"
        ) from exc

    found: dict[str, np.ndarray] = {}
    with h5py.File(str(path), "r") as f:
        datasets: dict[str, np.ndarray] = {}

        def visit(name: str, obj: Any) -> None:
            if isinstance(obj, h5py.Dataset):
                datasets[name] = obj

        f.visititems(visit)

        # A compound/structured dataset (one row per pulse) is the other plausible layout.
        # Collect first, then merge: expanding in place mutates the dict we are iterating.
        expanded: dict[str, np.ndarray] = {}
        for name, ds in datasets.items():
            if ds.dtype.names:
                for field in ds.dtype.names:
                    expanded[f"{name}/{field}"] = ds[field]
        datasets.update(expanded)

        toa = _match(datasets, TOA_ALIASES)
        freq = _match(datasets, FREQ_ALIASES)
        if toa is None or freq is None:
            raise TuringDatasetUnavailable(
                "Could not locate time-of-arrival and centre-frequency fields in "
                f"{Path(path).name}. Fields present: {sorted(datasets)[:40]}. "
                "Add the correct names to TOA_ALIASES / FREQ_ALIASES in this module."
            )
        found["toa"] = np.asarray(datasets[toa], dtype=np.float64).reshape(-1)
        found["frequency"] = np.asarray(datasets[freq], dtype=np.float64).reshape(-1)

    n = min(found["toa"].size, found["frequency"].size)
    return {"toa": found["toa"][:n], "frequency": found["frequency"][:n]}


def _match(datasets: dict[str, Any], aliases: Sequence[str]) -> str | None:
    """Prefer an exact leaf-name match, then fall back to a substring match."""
    by_leaf = {name: _normalise(name.split("/")[-1]) for name in datasets}
    for alias in aliases:
        for name, leaf in by_leaf.items():
            if leaf == alias:
                return name
    for alias in aliases:
        for name, leaf in by_leaf.items():
            if alias in leaf:
                return name
    return None


def map_frequencies_to_bands(frequencies: Iterable[float], num_bands: int = 10) -> np.ndarray:
    """Bin continuous centre frequencies into ``0 .. num_bands-1``.

    Equal-width bins over the observed ``[min, max]``. Equal-width rather than equal-count on
    purpose: the point of the replay is to preserve how unevenly real emitters are distributed
    across the spectrum, and quantile binning would flatten exactly that.
    """
    freqs = np.asarray(list(frequencies), dtype=np.float64)
    if freqs.size == 0:
        return np.zeros(0, dtype=np.int32)
    if num_bands < 1:
        raise ValueError("num_bands must be >= 1")

    lo, hi = float(np.min(freqs)), float(np.max(freqs))
    if hi <= lo:
        return np.zeros(freqs.size, dtype=np.int32)

    scaled = (freqs - lo) / (hi - lo) * num_bands
    return np.clip(scaled.astype(np.int32), 0, num_bands - 1)


def build_occupancy(
    toa: np.ndarray,
    bands: np.ndarray,
    num_bands: int,
    duration_steps: int = 2000,
    pulse_dwell_steps: int = 1,
) -> np.ndarray:
    """Quantise ``(time_of_arrival, band)`` pulses into a ``(duration_steps, num_bands)`` table.

    Time is rescaled so the whole recording spans ``duration_steps``; a pulse marks its band
    active for ``pulse_dwell_steps`` steps, which is what turns instantaneous pulses into the
    dwell windows a scanning receiver could actually catch.
    """
    occupancy = np.zeros((duration_steps, num_bands), dtype=bool)
    if toa.size == 0:
        return occupancy

    lo, hi = float(np.min(toa)), float(np.max(toa))
    steps = (
        np.zeros(toa.size, dtype=np.int64)
        if hi <= lo
        else ((toa - lo) / (hi - lo) * (duration_steps - 1)).astype(np.int64)
    )
    steps = np.clip(steps, 0, duration_steps - 1)

    for offset in range(max(1, pulse_dwell_steps)):
        shifted = np.clip(steps + offset, 0, duration_steps - 1)
        occupancy[shifted, bands] = True
    return occupancy


def build_replay_ground_truth(
    paths: Sequence[str | Path],
    num_bands: int = 16,
    duration_steps: int = 2000,
    pulse_dwell_steps: int = 2,
):
    """Turn one or more pulse-train files into a ReplayGroundTruth the environment accepts."""
    from ml.environments.spectrum import ReplayGroundTruth

    toas: list[np.ndarray] = []
    freqs: list[np.ndarray] = []
    for path in paths:
        pdw = extract_pdw_features(path)
        toas.append(pdw["toa"])
        freqs.append(pdw["frequency"])

    toa = np.concatenate(toas) if toas else np.zeros(0)
    frequency = np.concatenate(freqs) if freqs else np.zeros(0)
    order = np.argsort(toa)
    toa, frequency = toa[order], frequency[order]

    bands = map_frequencies_to_bands(frequency, num_bands)
    occupancy = build_occupancy(toa, bands, num_bands, duration_steps, pulse_dwell_steps)
    return ReplayGroundTruth(occupancy)


def load_replay_scenario(
    num_bands: int = 16,
    duration_steps: int = 2000,
    num_files: int = 1,
    split: str = "train",
    seed: int = 42,
    pulse_dwell_steps: int = 2,
    **env_kwargs,
):
    """Download, bin and wrap the dataset into a ready-to-step EWEnvironment.

    This is the Module-4-back-to-Module-1 join: every agent, metric and endpoint works unchanged,
    because only the ground-truth source has been swapped.
    """
    from ml.environments.environment import EWEnvironment

    paths = download_pulse_trains(num_files=num_files, split=split)
    ground_truth = build_replay_ground_truth(paths, num_bands, duration_steps, pulse_dwell_steps)
    return EWEnvironment(
        num_bands=num_bands,
        duration_steps=duration_steps,
        ground_truth=ground_truth,
        seed=seed,
        scenario_id="turing-replay",
        **env_kwargs,
    )
